### PR TITLE
Fixes issue with broken-up stdout output

### PR DESCRIPTION
**Pull request by mziter**
Fixes issue sharkdp/hexyl#47 by wrapping StdoutLock in BufWriter. This will make sure output is written in chunks, which should lessen the annoyance when other processes write to stdout during the same window as hexyl.

### CODE REVIEW

**Comment by selfup** [comment]
Nice! Adding screenshots to show that the `Done!` case will as expected be quite impossible :joy: 

screenshot from 2019-02-04 06-50-28

***

```bash
hexyl (master) $ (echo Er... >&2; sleep 0.2;  echo Thinking... >&2; sleep 0.2;  echo Um... >&2; sleep 0.2;  echo Output, finally;  echo 'Done!' >&2) | target/release/hexyl 
Er...
Thinking...
Um...
Done!
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 4f 75 74 70 75 74 2c 20 ┊ 66 69 6e 61 6c 6c 79 0a │Output, ┊finally_│
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```

**Comment by sharkdp** [comment]
@mziter Thank you very much for working on this!

Is there any chance that this could cause unwanted behavior in some cases? What if `hexyl` is reading input from STDIN (from the keyboard)? Would the output always be present when the user submits a new line?

Couldn't we just wait with printing the header until we actually write the first line of (actual) output?

**Comment by mziter** [comment]
@sharkdp 
Glad to help. I am new to Rust and open-source work.  I believe I tested the STDIN scenario you describe and the buffer is still flushed, but I will check again now.
The reason I chose to go the buffer route is that I believe the issue really isn't just the header row, but more general. If we expanded FauxFaux's script in his submittted issue, I think we would have seen a lot of other lines broken up as well. When any other processess write to STDOUT they will "interrupt" our pretty output. Using the buffer at least large chunks will get written together. I may try to expand FauxFaux's script to illustrate my point.

**Comment by sharkdp** [comment]
Thank you for the detailed response.

I don't really care too much about the interactive-input scenario, but I'm concerned that there might be a output latency in general, when we introduce the buffered writer.

My question would be: do we really have to support a scenario where a second process is printing to the terminal at the same time?! What would be a use case for this? I see the `( echo Er.. >&2; sleep ...` snippet more like a way to demonstrate that the header is printed early (which could be fixed).

**Comment by mziter** [comment]
I just saw the buffer as a simple way to solve the solution and other similiar problems. I am new to Rust and system languages in general and appreciate your feedback.

I just did a simple benchmark on a large .png file and I do see a significant performance decrease using the extra buffer, so you were obviously right to be concerned. I can do as you suggested and handle just the header row.

I am going to be traveling for most of today, so I may not get to it until tomorrow. Two questions:i
* What is best way to ignore these changes I already made? Cancel the PR and create a new one?
* For implementing change for just the header row, would a bool on the printer be best option to see if header has been printed yet or not?

**Comment by sharkdp** [comment]
> I can do as you suggested and handle just the header row.

 That sounds great, thank you.

> * What is best way to ignore these changes I already made? Cancel the PR and create a new one?

That's probably the easiest way. You can also force-push only the new commits on your branch, if you like.

> * For implementing change for just the header row, would a bool on the printer be best option to see if header has been printed yet or not?

Sounds like a good idea to me, yes.

**Comment by mziter** [comment]
Opening a new pull request with solutioning discussed above.

**Comment by mziter** [comment]
Opening new pull request #51

**Pull request closed without merging**
